### User sign up endpoint 
POST http://localhost:5000/v1/user/
Content-Type: application/json

{
   "name": "Ashraful Islam",
   "company": "Company name",
   "address": "Shibpur, Narsingdi",
   "phone": "013098999999",
   "email": "example9@gmail.com",
   "password": "scrept123"
}

### User sign in endpoint
POST http://localhost:5000/v1/user/login
Content-Type: application/json

{
   "email": "example9@gmail.com",
   "password": "scrept123"
}


### Get a user profile endpoint
GET http://localhost:5000/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGU5QGdtYWlsLmNvbSIsImlhdCI6MTY1NzY5Mjc4MCwiZXhwIjoxNjU3NjkyODQwfQ.M4XqA_Py7urOLwr5bTdWR67MSxBGmEJiQcQtptQ9MsY

### Get a user refresh token
GET http://localhost:5000/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGU5QGdtYWlsLmNvbSIsImlhdCI6MTY1NzY5MjE3NCwiZXhwIjoxNjYwMjg0MTc0fQ.BVfkFX1INSvid3i-L0UI7rMu6JS3Yi95kbQliGM0178



